spring:  
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/blogApp
    username: root
    
# create , create-drop , validate, update, none
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
 
    
    

    