spring:
   datasource:
      password: root
      url: jdbc:mysql://localhost:3306/blogApp
      username: root
   jpa:
# create , create-drop , validate, update, none
      hibernate:
         ddl-auto: update
      show-sql: true
      
      
