eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
     
spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
      - id: couponService
        uri: lb://COUPON-SERVICE
        predicates: Path=/coupons/**
        
      - id: productService
        uri: lb://PRODUCT-SERVICE
        predicates: Path=/products/**
        
        
#  zipkin:
#    base-url: http://127.0.0.1:9411/
        
        
     
          
    
    
